version: '2.0'
services:

  patterns_dashboard:
    build: ./
    platform: linux/amd64
    environment:
      - NODE_ENV=prod
    restart: unless-stopped
    networks:
      - f2cm_default
    ports:
      - 5000:80

networks:
  f2cm_default:
    name: "f2cm_default"
